<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="school" nsURI="eu.mondo.map.modelanalyzer.emf.tests.schoolmodel"
    nsPrefix="school">
  <eClassifiers xsi:type="ecore:EClass" name="Person" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Student" eSuperTypes="#//Person"/>
  <eClassifiers xsi:type="ecore:EClass" name="Teacher" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EReference" name="teach" upperBound="-1"
        eType="#//Student"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eStructuralFeatures xsi:type="ecore:EReference" name="people" upperBound="-1"
        eType="#//Person" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
